### ISSUE TITLE
Sporadic errors from WeatherManResponse#initialize

### ISSUE THREAD

**Issue by nikitar** [jdpace/weatherman#2]
For example, like this one

```
NoMethodError (You have a nil object when you didn't expect it!
You might have expected an instance of ActiveRecord::Base.
The error occurred while evaluating nil.[]):
/Library/Ruby/Gems/1.8/gems/jdpace-weatherman-0.1.2/lib/weather_man_response.rb:16:in `initialize'
/Library/Ruby/Gems/1.8/gems/jdpace-weatherman-0.1.2/lib/weather_man.rb:47:in `new'
/Library/Ruby/Gems/1.8/gems/jdpace-weatherman-0.1.2/lib/weather_man.rb:47:in `fetch'
```

After playing around with weather.com response, it looks like simple_xml object there has format

```
 {"weather"=> {
    #...
    "head"=>{
      "ud"=>"km",
      "up"=>"mb",
      "form"=>"MEDIUM", 
      "ur"=>"mm",
      "us"=>"km/h",
      "locale"=>"en_US",
      "ut"=>"C"
    },
    #...
```

While in the code it's being referenced without top-level 'weather' object and with lots of arrays (e.g. simple_xml['head'][0]['ut'][0]).

The strangest thing is that I've seen this problem to appear and disappear twice already, while data format from weather.com stays the same.

Do you have any idea what might the cause? Right now I'm waiting for the next period when it's working, so I could test it a little more.

simple-xml versions tried 1.0.11 and 1.0.12

Thank you,
Nikita

**Comment by nikitar** [comment]
It was monkeypatch by Amazon S3 gem, which has overridden XmlSimple.xml_in behaviour. Therefore, close.
